/* Pathfinding.h
   Self-conatined pathfinding
   Functions providing A* pathfinding. 
   Most require some sort of moement-cost map (to path routes).
*/
#pragma once

#include "SFML\System.hpp"

//UNITTYPE provides information to generateCostMap on the cost of different types of terrian
enum UNITTYPE {WATER, LAND, AIR};

struct node{
	node *parent;
	int gScore;
	int hScore;
	int fScore;
	sf::Vector2i nodePos;
};

// generateCostMap returns the cost of each going onto each tile on the overall world map for a particular type of unit
//   - int **map is the world map where 0 is water and 1 is land
//   - sf::Vector2i mapSize equal to height and width of map
//   - UNITTYPE type tells the function what tiles the unit can access (LAND can acess land tiles, etc) 
int **generateCostMap(int **map, sf::Vector2i mapSize, UNITTYPE type);

// generateRoute returns a list of sub destinations that the unit then follows to the destination
//   - int **costMap is the cost of movment for each tile (generated by generateCostMap)
//   - sf::Vector2f unitLoc is the starting location of the unit
//   - sf::Vector2f unitDest is the final destination of the unit
sf::Vector2f *generateRoute(int **costMap, sf::Vector2f unitLoc, sf::Vector2f unitDest);
